VehicleSale/Controllers/FeaturesMastersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassLibrary1;
using VehicleSale.ViewModels;
using System.IO;

namespace VehicleSale.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class FeaturesMastersController : Controller
    {
        private VehicleSaleEntities db = new VehicleSaleEntities();

        // GET: FeaturesMasters
        public ActionResult Index()
        {
            var featuresMasters = db.FeaturesMasters.Include(f => f.AmentiesMaster);
            return View(featuresMasters.ToList());
        }

        // GET: FeaturesMasters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeaturesMaster featuresMaster = db.FeaturesMasters.Find(id);
            if (featuresMaster == null)
            {
                return HttpNotFound();
            }
            return View(featuresMaster);
        }

        // GET: FeaturesMasters/Create
        public ActionResult Create()
        {
            ViewBag.AmentiesID = new SelectList(db.AmentiesMasters, "ID", "Name");
            return View();
        }

        // POST: FeaturesMasters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AmentiesID,Title,Description,IsActive")] FeaturesMasterVM featuresMastervm, HttpPostedFileBase ImageUrl)
        {
            if (ImageUrl == null)
            {
                ModelState.AddModelError("ImageUrl", "Please select image");
            }
            if (ModelState.IsValid)
            {
                FeaturesMaster featuresmaster = new FeaturesMaster();
                if (ImageUrl != null && ImageUrl.ContentLength > 0)
                {
                    HttpFileCollectionBase file = Request.Files;
                    DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                    for (int i = 0; i < file.Count; i++)
                    {
                        HttpPostedFileBase files = file[i];
                        if (!string.IsNullOrEmpty(Path.GetFileName(files.FileName)))
                        {
                            var fileName = Guid.NewGuid() + Path.GetFileName(files.FileName);
                            string path = Server.MapPath("~/ProductImage/") + fileName;
                            dt.Rows.Add(files.FileName);
                            featuresmaster.ImageUrl = "/ProductImage/" + fileName;
                            files.SaveAs(path);

                        }
                    }
                }
                
                featuresmaster.ID = featuresMastervm.ID;
                featuresmaster.AmentiesID = featuresMastervm.AmentiesID;
                featuresmaster.Description = featuresMastervm.Description;
                featuresmaster.IsActive = true;
                featuresmaster.Title = featuresMastervm.Title;
                db.FeaturesMasters.Add(featuresmaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AmentiesID = new SelectList(db.AmentiesMasters, "ID", "Name", featuresMastervm.AmentiesID);
            return View(featuresMastervm);
        }

        // GET: FeaturesMasters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeaturesMaster featuresMaster = db.FeaturesMasters.Find(id);
            FeaturesMasterVM featuresMasterVM = new FeaturesMasterVM();            
            featuresMasterVM.ID = featuresMaster.ID;
            featuresMasterVM.Description = featuresMaster.Description;
            featuresMasterVM.ImageUrl = featuresMaster.ImageUrl;
            featuresMasterVM.AmentiesID = featuresMaster.AmentiesID;
            featuresMasterVM.IsActive = featuresMaster.IsActive;
            featuresMasterVM.Title = featuresMaster.Title;
            if (featuresMaster == null)
            {
                return HttpNotFound();
            }

            ViewBag.AmentiesID = new SelectList(db.AmentiesMasters, "ID", "Name", featuresMaster.AmentiesID);
            return View(featuresMasterVM);
        }

        // POST: FeaturesMasters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AmentiesID,Title,Description,IsActive")] FeaturesMasterVM featuresMastervm, HttpPostedFileBase ImageUrl)
        {
            //if (ImageUrl == null)
            //{
            //    ModelState.AddModelError("ImageUrl", "Please select image");
            //}
            if (ModelState.IsValid)
            {
                FeaturesMaster featuresmaster = db.FeaturesMasters.Where(am => am.ID == featuresMastervm.ID).FirstOrDefault();
                if (ImageUrl != null && ImageUrl.ContentLength > 0)
                {

                    HttpFileCollectionBase file = Request.Files;
                    DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                    for (int i = 0; i < file.Count; i++)
                    {
                        HttpPostedFileBase files = file[i];
                        if (!string.IsNullOrEmpty(Path.GetFileName(files.FileName)))
                        {
                            var fileName = Guid.NewGuid() + Path.GetFileName(files.FileName);
                            string path = Server.MapPath("~/ProductImage/") + fileName;
                            dt.Rows.Add(files.FileName);
                            files.SaveAs(path);
                            featuresmaster.ImageUrl = "/ProductImage/" + fileName;
                        }
                    }
                }
                featuresmaster.ID = featuresMastervm.ID;
                featuresmaster.AmentiesID = featuresMastervm.AmentiesID;
                featuresmaster.Description = featuresMastervm.Description;
                featuresmaster.IsActive = true;
                featuresmaster.Title = featuresMastervm.Title;
                db.Entry(featuresmaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AmentiesID = new SelectList(db.AmentiesMasters, "ID", "Name", featuresMastervm.AmentiesID);
            return View(featuresMastervm);
        }

        [HttpPost]
        public ActionResult ImageDelete(int? id)
        {
            FeaturesMaster FeaturesMaster = db.FeaturesMasters.Find(id);

            if (FeaturesMaster == null)
            {
                return HttpNotFound();
            }

            FeaturesMaster.ImageUrl = null;
            db.Entry(FeaturesMaster).State = EntityState.Modified;
            db.SaveChanges();
            return Content("true");
        }

        // GET: FeaturesMasters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeaturesMaster featuresMaster = db.FeaturesMasters.Find(id);
            if (featuresMaster == null)
            {
                return HttpNotFound();
            }
            return View(featuresMaster);
        }

        // POST: FeaturesMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FeaturesMaster featuresMaster = db.FeaturesMasters.Find(id);
            db.FeaturesMasters.Remove(featuresMaster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VehicleSale/Views/FeaturesMasters/Create.cshtml
@model VehicleSale.ViewModels.FeaturesMasterVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Features Master</h3>
    </header>
    <div class="panel-body">


        @using (Html.BeginForm(Html.BeginForm("Create", "FeaturesMasters", FormMethod.Post, new { @class = "form-horizontal", @id = "form", enctype = "multipart/form-data" })))
        {
            @Html.AntiForgeryToken()

            <div class="col-sm-6">
               
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.AmentiesID, "Amenties")

                    @Html.DropDownList("AmentiesID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AmentiesID, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title)

                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

                </div>
               
                <div class="form-group">
                    @Html.LabelFor(model => model.Description)

                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ImageUrl, "Image")
                    @Html.TextBoxFor(m => m.ImageUrl, new { type = "file" })

                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">

                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-primary" })
                </div>
            </div>
        }

    </div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VehicleSale/Views/FeaturesMasters/Delete.cshtml
@model ClassLibrary1.FeaturesMaster

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Features Master</h3>
    </header>
    <div class="panel-body">
        <h3>Are you sure you want to delete this?</h3>
        <div>

            <dl class="">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.AmentiesMaster.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AmentiesMaster.Name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-primary" /> 
                    @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-primary" })
                </div>
            }
        </div>
    </div>
</section>

VehicleSale/Views/FeaturesMasters/Edit.cshtml
@model VehicleSale.ViewModels.FeaturesMasterVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Features Master</h3>
    </header>
    <div class="panel-body">


        @using (Html.BeginForm("Edit", "FeaturesMasters", FormMethod.Post, new { @class = "form-horizontal", @id = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="col-sm-6">
                <h4>FeaturesMaster</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)

                <div class="form-group">
                    @Html.LabelFor(model => model.AmentiesID, "Amenties")

                    @Html.DropDownList("AmentiesID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AmentiesID, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title)

                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description)

                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                </div>
                @if (Model.ImageUrl != null)
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl)
                        <img src=@Html.DisplayFor(modelItem => modelItem.ImageUrl) alt="" width="200" height="200" />
                        <i class="fa fa-times" aria-hidden="true" vehicleid="@Model.ID" id="Cross_image"></i>
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                    </div>
                }
                else
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl)
                        <input id="ImageUrl" name="ImageUrl" required type="file" class="file form-control" data-preview-file-type="text">
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                    </div>

                }

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-primary" })



                </div>
            </div>
        }

    </div>
</section>
<script type="text/javascript">
    $('#Cross_image').click(function () {
        if (confirm("Do you want to delete image?")) {
            var id = $("#Cross_image").attr("vehicleid");
            //alert("do you want to delete image?");
            $.ajax({
                url: "/FeaturesMasters/ImageDelete?id=" + id,
                type: "post", success: function (data) {
                    if (data == 'true') {
                        location.reload();
                        //window.location.reload();
                    }
                    return true;
                }, error: function (data) {
                    return false;
                }
            });
        }
    }); 

</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VehicleSale/Views/FeaturesMasters/Index.cshtml
@model IEnumerable<ClassLibrary1.FeaturesMaster>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Features Master</h3>
    </header>
    <div class="panel-body">

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    Amenties
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>Image</th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AmentiesMaster.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                   
                    <td>
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" height="100" width="100" alt="">
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }
        </table>
    </div>
</section>