VehicleSale/Controllers/AmentiesMastersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassLibrary1;
using System.IO;
using VehicleSale.ViewModels;

namespace VehicleSale.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class AmentiesMastersController : Controller
    {
        private VehicleSaleEntities db = new VehicleSaleEntities();

        // GET: AmentiesMasters
        public ActionResult Index()
        {
            return View(db.AmentiesMasters.ToList());
        }

        // GET: AmentiesMasters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmentiesMaster amentiesMaster = db.AmentiesMasters.Find(id);
            if (amentiesMaster == null)
            {
                return HttpNotFound();
            }
            return View(amentiesMaster);
        }

        // GET: AmentiesMasters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AmentiesMasters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description")] AmentiesMasterVM amentiesMastervm, HttpPostedFileBase ImageUrl)
        {
            AmentiesMaster amentiesMaster = new AmentiesMaster();
            if (ImageUrl == null )
            {
                ModelState.AddModelError("ImageUrl", "Please select image");
            }

            if (ModelState.IsValid)
            {
                if (ImageUrl != null && ImageUrl.ContentLength > 0)
                {
                    HttpFileCollectionBase file = Request.Files;
                    DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                    for (int i = 0; i < file.Count; i++)
                    {
                        HttpPostedFileBase files = file[i];
                        if (!string.IsNullOrEmpty(Path.GetFileName(files.FileName)))
                        {
                            var fileName = Guid.NewGuid() + Path.GetFileName(files.FileName);
                            string path = Server.MapPath("~/ProductImage/") + fileName;
                            dt.Rows.Add(files.FileName);
                            amentiesMaster.ImageUrl = "/ProductImage/" + fileName;
                            files.SaveAs(path);

                        }
                    }
                }
                amentiesMaster.Name = amentiesMastervm.Name;
                amentiesMaster.Description = amentiesMastervm.Description;
                amentiesMaster.ID = amentiesMastervm.ID;
                amentiesMaster.IsActive = true;
                db.AmentiesMasters.Add(amentiesMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amentiesMastervm);
        }

        // GET: AmentiesMasters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmentiesMaster amentiesMaster = db.AmentiesMasters.Find(id);
            AmentiesMasterVM amentiesMastervm = new AmentiesMasterVM();
            amentiesMastervm.ID = amentiesMaster.ID;
            amentiesMastervm.ImageUrl = amentiesMaster.ImageUrl;
            amentiesMastervm.Description = amentiesMaster.Description;
            amentiesMastervm.IsActive = amentiesMaster.IsActive;
            amentiesMastervm.Name = amentiesMaster.Name;
            if (amentiesMaster == null)
            {
                return HttpNotFound();
            }
            return View(amentiesMastervm);
        }

        // POST: AmentiesMasters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description")] AmentiesMasterVM amentiesMastervm, HttpPostedFileBase ImageUrl)
        {
            
            if (ModelState.IsValid)
            {
                AmentiesMaster amentiesMaster = db.AmentiesMasters.Where(am => am.ID == amentiesMastervm.ID).FirstOrDefault();
                if (ImageUrl != null && ImageUrl.ContentLength > 0)
                {

                    HttpFileCollectionBase file = Request.Files;
                    DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                    for (int i = 0; i < file.Count; i++)
                    {

                        HttpPostedFileBase files = file[i];
                        if (!string.IsNullOrEmpty(Path.GetFileName(files.FileName)))
                        {
                            var fileName = Guid.NewGuid() + Path.GetFileName(files.FileName);
                            string path = Server.MapPath("~/ProductImage/") + fileName;
                            dt.Rows.Add(files.FileName);
                            files.SaveAs(path);
                            amentiesMaster.ImageUrl = "/ProductImage/" + fileName;
                          
                        }
                    }
                }
                amentiesMaster.Description = amentiesMastervm.Description;
                amentiesMaster.ID = amentiesMastervm.ID;
                amentiesMaster.Name = amentiesMastervm.Name;
                amentiesMaster.IsActive = true;
                db.Entry(amentiesMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(amentiesMastervm);
        }

        // GET: AmentiesMasters/Delete/5
        [HttpPost]
        public ActionResult ImageDelete(int? id)
        {
            AmentiesMaster AmentiesMaster = db.AmentiesMasters.Find(id);

            if (AmentiesMaster == null)
            {
                return HttpNotFound();
            }

            AmentiesMaster.ImageUrl = null;
            db.Entry(AmentiesMaster).State = EntityState.Modified;
            db.SaveChanges();
            return Content("true");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmentiesMaster amentiesMaster = db.AmentiesMasters.Find(id);
            if (amentiesMaster == null)
            {
                return HttpNotFound();
            }
            return View(amentiesMaster);
        }

        // POST: AmentiesMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AmentiesMaster amentiesMaster = db.AmentiesMasters.Find(id);
            db.AmentiesMasters.Remove(amentiesMaster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VehicleSale/Views/AmentiesMasters/Create.cshtml
@model VehicleSale.ViewModels.AmentiesMasterVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Amenties Master</h3>
    </header>
    <div class="panel-body">
        @using (Html.BeginForm("Create", "AmentiesMasters", FormMethod.Post, new { @class = "form-horizontal", @id = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="col-sm-6">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name)

                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description)
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ImageUrl, "Image")
                    @Html.TextBoxFor(m => m.ImageUrl, new { type = "file" })
                    @*<input id="ImageUrl" name="ImageUrl" type="file" class="file form-control" data-preview-file-type="text">*@
                    @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">

                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-primary" })
                </div>
            </div>
        }

    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VehicleSale/Views/AmentiesMasters/Delete.cshtml
@model ClassLibrary1.AmentiesMaster

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Amenties Master</h3>
    </header>
    <div class="panel-body">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
         
            <dl class="">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>



            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-primary" /> |
                    @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-primary" })
                </div>
            }
        </div>
    </div>
</section>

VehicleSale/Views/AmentiesMasters/Edit.cshtml
@model VehicleSale.ViewModels.AmentiesMasterVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Amenties Master</h3>
    </header>
    <div class="panel-body">

        @using (Html.BeginForm("Edit", "AmentiesMasters", FormMethod.Post, new { @class = "form-horizontal", @id = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="col-sm-6">
                <h4>AmentiesMaster</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })

                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                </div>

                @if (Model.ImageUrl != null)
                {

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl)
                    
                        <img src=@Html.DisplayFor(modelItem => modelItem.ImageUrl)  alt="" width="200" height="200" />
                        <i class="fa fa-times" aria-hidden="true" vehicleid="@Model.ID" id="Cross_image"></i>
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                    </div>
                }
                else
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageUrl)

                        <input id="ImageUrl" name="ImageUrl" type="file" required accept="image/*" class="file form-control" data-preview-file-type="text">
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                    </div>

                }
                <div class="form-group">

                    <input type="submit" value="Save"  class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-primary" })
                </div>
            </div>
        }

    </div>
</section>
<script type="text/javascript">
    //function validate()
    //{
    //    if(ImageUrl)
    //}
    $('#Cross_image').click(function () {
        if (confirm("Do you want to delete image?")) {
            var id = $("#Cross_image").attr("vehicleid");
            //alert("do you want to delete image?");
            $.ajax({
                url: "/AmentiesMasters/ImageDelete?id=" + id,
                type: "post", success: function (data) {
                    if (data == 'true') {
                        location.reload();
                        //window.location.reload();
                    }
                    return true;
                }, error: function (data) {
                    return false;
                }
            });
        }
    });

    $('#save_data').click(function () {
        var imageurl = $('#ImageUrl').val();
        if (imageurl == "") {
            alert("Please Upload File.")
            return false;
        }

    });


</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VehicleSale/Views/AmentiesMasters/Index.cshtml
@model IEnumerable<ClassLibrary1.AmentiesMaster>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Amenties Master</h3>
    </header>
    <div class="panel-body">

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>

                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" height="100" width="100" alt="">
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
</section>