VehicleSale/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace VehicleSale.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

VehicleSale/Controllers/VehicleImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassLibrary1;
using System.IO;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using System.Web.Configuration;

namespace VehicleSale.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class VehicleImagesController : Controller
    {

        private VehicleSaleEntities db = new VehicleSaleEntities();

        // GET: VehicleImages
        public ActionResult Index(int? Id)
        {
            var vehicleImages = db.VehicleImages.Where(v => v.VehicleID == Id).Include(v => v.Vehicle);
            ViewBag.ID = Id;
            return View(vehicleImages.ToList());
        }

        // GET: VehicleImages/Create
        public ActionResult Create(int? Id)
        {
            ViewBag.VehicleID = new SelectList(db.Vehicles.Where(v => v.ID == Id), "ID", "Title");
            ViewBag.ID = Id;
            return View();
        }
        Account account = new Account(WebConfigurationManager.AppSettings["CloudName"],
             WebConfigurationManager.AppSettings["ApiKey"],
             WebConfigurationManager.AppSettings["ApiSecret"]);
        // POST: VehicleImages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,VehicleID,VideoUrl")] VehicleImage vehicleImage, HttpPostedFileBase ImageUrl, int? Id)
        {
            if (ImageUrl == null)
            {
                ModelState.AddModelError("ImageUrl", "Please select image");
            }
            if (ModelState.IsValid)
            {
                Cloudinary cloudinary = new Cloudinary(account);
                vehicleImage.IsActive = true;
                vehicleImage.VehicleID = Id;
                ViewBag.ID = vehicleImage.VehicleID;
                if (ImageUrl != null && ImageUrl.ContentLength > 0)
                {
                    HttpFileCollectionBase file = Request.Files;
                    DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                    for (int i = 0; i < file.Count; i++)
                    {
                        HttpPostedFileBase files = file[i];
                        if (!string.IsNullOrEmpty(Path.GetFileName(files.FileName)))
                        {
                            var fileName = Guid.NewGuid() + Path.GetFileName(files.FileName);
                            string path = Server.MapPath("~/ProductImage/") + fileName;
                            dt.Rows.Add(files.FileName);
                            vehicleImage.ImageUrl = "/ProductImage/" + fileName;
                            files.SaveAs(path);
                            var uploadParams = new ImageUploadParams()
                            {
                                File = new FileDescription(path)
                            };
                            var uploadResult = cloudinary.Upload(uploadParams);
                            vehicleImage.PublicKey = uploadResult.PublicId;
                        }
                    }
                }
                db.VehicleImages.Add(vehicleImage);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = Id });
            }

            ViewBag.VehicleID = new SelectList(db.Vehicles, "ID", "Title", vehicleImage.VehicleID);
            return View(vehicleImage);
        }

        // GET: VehicleImages/Edit/5
        public ActionResult Edit(int? id)
        {           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleImage vehicleImage = db.VehicleImages.Find(id);
            ViewBag.ID = vehicleImage.VehicleID;
            if (vehicleImage == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleID = new SelectList(db.Vehicles.Where(v => v.ID == vehicleImage.VehicleID), "ID", "Title", vehicleImage.VehicleID);
            return View(vehicleImage);
        }

        // POST: VehicleImages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,VehicleID,VideoUrl")] VehicleImage vehicleImage, HttpPostedFileBase ImageUrl)
        {
            Cloudinary cloudinary = new Cloudinary(account);
            if (ModelState.IsValid)
            {
                vehicleImage.IsActive = true;
                if (!string.IsNullOrEmpty(Request.Form["hdnVehicleID"]))
                {
                    vehicleImage.VehicleID = Convert.ToInt32(Request.Form["hdnVehicleID"]);
                    ViewBag.ID = vehicleImage.VehicleID;
                }
                // var vehiclecode = db.Vehicles.Where(x => x.ID == vehicleImage.VehicleID).FirstOrDefault();
                var olddata = db.VehicleImages.Find(vehicleImage.ID);
                if (olddata != null)
                {
                    vehicleImage.ImageUrl = olddata.ImageUrl;
                    vehicleImage.PublicKey = olddata.PublicKey;                   
                }
                if (ImageUrl != null && ImageUrl.ContentLength > 0)
                {

                    HttpFileCollectionBase file = Request.Files;
                    DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                    for (int i = 0; i < file.Count; i++)
                    {

                        HttpPostedFileBase files = file[i];
                        if (!string.IsNullOrEmpty(Path.GetFileName(files.FileName)))
                        {
                            //if (!System.IO.Directory.Exists(Server.MapPath(@"~/"+vehiclecode.VehicleCode+"/")))
                            //{
                            //    System.IO.Directory.CreateDirectory(Server.MapPath(@"~/" + vehiclecode.VehicleCode + "/"));
                            //}


                            var fileName = Guid.NewGuid() + Path.GetFileName(files.FileName);
                            string path = Server.MapPath("~/ProductImage/") + fileName;
                            dt.Rows.Add(files.FileName);
                            vehicleImage.ImageUrl = "/ProductImage/" + fileName;
                            files.SaveAs(path);
                            var uploadParams = new ImageUploadParams()
                            {
                                File = new FileDescription(path)
                            };
                            var uploadResult = cloudinary.Upload(uploadParams);
                            vehicleImage.PublicKey = uploadResult.PublicId;
                          
                        }
                    }
                }
                using (var context =  new VehicleSaleEntities())
                {
                    context.Entry(vehicleImage).State = EntityState.Modified;
                    context.SaveChanges();
                }
                return RedirectToAction("Index", new { id = vehicleImage.VehicleID });
            }
            ViewBag.VehicleID = new SelectList(db.Vehicles, "ID", "Title", vehicleImage.VehicleID);
            return View(vehicleImage);
        }

        // GET: VehicleImages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleImage vehicleImage = db.VehicleImages.Find(id);
            ViewBag.ID = vehicleImage.VehicleID;
            if (vehicleImage == null)
            {
                return HttpNotFound();
            }
            return View(vehicleImage);
        }

        // POST: VehicleImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VehicleImage vehicleImage = db.VehicleImages.Find(id);
            ViewBag.ID = vehicleImage.VehicleID;
            db.VehicleImages.Remove(vehicleImage);
            
            db.SaveChanges();
            return RedirectToAction("Index", new { id = ViewBag.ID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SaveUploadedFile(int? Id)
        {
            Cloudinary cloudinary = new Cloudinary(account);
            bool isSavedSuccessfully = true;
            string fName = "";
            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
                VehicleImage objImg = new VehicleImage();
                DataTable dt = new DataTable { Columns = { new DataColumn("Path") } };
                //Save file content goes here
                fName = file.FileName;
                if (file != null && file.ContentLength > 0)
                {
                    var fileName1 = Guid.NewGuid() + Path.GetFileName(file.FileName);
                    string path = Server.MapPath("~/ProductImage/") + fileName1;
                    dt.Rows.Add(file.FileName);
                    objImg.ImageUrl = "/ProductImage/" + fileName1;
                    file.SaveAs(path);
                    var uploadParams = new ImageUploadParams()
                    {
                        File = new FileDescription(path)
                    };

VehicleSale/Views/VehicleImages/Create.cshtml
@model ClassLibrary1.VehicleImage

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ID = ViewBag.ID;
}
<link href="~/Content/dropzone/css/dropzone.css" rel="stylesheet" />
<script src="~/Content/dropzone/dropzone.js"></script>
<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Vehicle Images</h3>
    </header>
    <div class="panel-body">
        @*@using (Html.BeginForm("Create", "VehicleImages", FormMethod.Post, new { @class = "form-horizontal", @id = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="col-sm-6">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.VehicleID, "Vehicle")

                    @Html.DropDownList("VehicleID", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.VehicleID, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ImageUrl, "Image")
                    <input id="ImageUrl" name="ImageUrl" type="file" class="file form-control" data-preview-file-type="text">
                
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.VideoUrl, "Video Url ( if available)")
                    @Html.EditorFor(model => model.VideoUrl, new { htmlAttributes = new { @class = "form-control" } })
                </div>*@
             
                @*
                <div class="form-group">

                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", "VehicleImages", new { id = ID }, new { @class = "btn btn-primary" })


                </div>
            </div>
        }*@
        <form action="~/VehicleImages/SaveUploadedFile/@ID" method="post" enctype="multipart/form-data" class="dropzone" id="dropzoneForm">
            <div class="fallback" style="display:none;">
                <input name="file" type="file" />
                @*<input type="submit" value="Upload" />*@
            </div>
        </form>
        <div class="partialContents" data-url="/VehicleImages/Manage/@ID">
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        $('input[type=file]').change(function () {
            var val = $(this).val().toLowerCase();
            var regex = new RegExp("(.*?)\.(jpg|jpeg|bmp|gif|png)$");
            if (!(regex.test(val))) {
                $(this).val('');
                alert('Please select correct file format');
            }
        });
    });
    Dropzone.options.dropzoneForm = {
        acceptedFiles: "image/*",
        maxFiles: 12,
        init: function () {
            this.on("maxfilesexceeded", function (data) {
                var res = eval('(' + data.xhr.responseText + ')');
            });
            this.on("addedfile", function (file) {

                setTimeout(callback, 1000);
            });
        }
    };
    function callback() {
        var url = $(".partialContents").data("url");
        if (url && url.length > 0) {
            $(".partialContents").load(url);
        }
    }
    $(function () {
        callback();
    });
</script>
<style>
    .fallback {
        display: block !important;
    }
</style>

VehicleSale/Views/VehicleImages/Delete.cshtml
@model ClassLibrary1.VehicleImage
@using System.Web.Configuration;
@using CloudinaryDotNet;
@using CloudinaryDotNet.Actions

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ID = ViewBag.ID;
    Account account = new Account(WebConfigurationManager.AppSettings["CloudName"],
                             WebConfigurationManager.AppSettings["ApiKey"],
                             WebConfigurationManager.AppSettings["ApiSecret"]);
    Cloudinary cloudinary = new Cloudinary(account);
}
<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Vehicle Images</h3>
    </header>
    <div class="panel-body">
        <h3>Are you sure you want to delete this?</h3>
        <div>

            <dl class="">
                <dt>
                    @Html.DisplayName("Image")
                </dt>

                <dd>
                    @*@Html.DisplayFor(model => model.ImageUrl)*@
                    @cloudinary.Api.UrlImgUp.Transform(new Transformation().Width(200).Height(200).Crop("fill")).BuildImageTag(Model.PublicKey)


                </dd>

               

                <dt>
                    @Html.DisplayName("Fleet Title")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Vehicle.Title)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-primary" /> |
                    @Html.ActionLink("Back to List", "Index", "VehicleImages", new { id = ID }, new { @class = "btn btn-primary" })
                </div>
            }
        </div>
    </div>
</section>

VehicleSale/Views/VehicleImages/Edit.cshtml
@model ClassLibrary1.VehicleImage

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ID = ViewBag.ID;
}
<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Vehicle Images</h3>
    </header>
    <div class="panel-body">


        @using (Html.BeginForm(Html.BeginForm("Edit", "VehicleImages", FormMethod.Post, new { @class = "form-horizontal", @id = "form", enctype = "multipart/form-data" })))
        {
            <div class="col-sm-6">
                @Html.AntiForgeryToken()

                <input type="hidden" name="hdnVehicleID" id="hdnVehicleID" value="@ID" />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)

                <div class="form-group">
                    @Html.LabelFor(model => model.VehicleID, "Vehicle")

                    @Html.DropDownList("VehicleID", null, htmlAttributes: new { @class = "form-control" , @disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.VehicleID, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })

                    <input id="ImageUrl" name="ImageUrl" type="file" class="file form-control" data-preview-file-type="text">
              
                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })

                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.VideoUrl, "Video Url ( if available)")
                    @Html.EditorFor(model => model.VideoUrl, new { htmlAttributes = new { @class = "form-control" } })
            


                </div>*@

                <div class="form-group">

                    <input type="submit" value="Save" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", "VehicleImages", new { id = ID }, new { @class = "btn btn-primary" })


                </div>
            </div>
        }
      
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        $('input[type=file]').change(function () {
            var val = $(this).val().toLowerCase();
            var regex = new RegExp("(.*?)\.(jpg|jpeg|bmp|gif|png)$");
            if (!(regex.test(val))) {
                $(this).val('');
                alert('Please select correct file format');
            }
        });
    });
   
</script>

VehicleSale/Views/VehicleImages/Index.cshtml
@model IEnumerable<ClassLibrary1.VehicleImage>
@using System.Web.Configuration;
@using CloudinaryDotNet;
@using CloudinaryDotNet.Actions
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ID = ViewBag.ID;
    Account account = new Account(WebConfigurationManager.AppSettings["CloudName"],
                               WebConfigurationManager.AppSettings["ApiKey"],
                               WebConfigurationManager.AppSettings["ApiSecret"]);
    Cloudinary cloudinary = new Cloudinary(account);
}

<section class="panel panel-info">
    <header class="panel-heading">
        <h3 class="panel-title">Vehicle Images</h3>
    </header>
    <div class="panel-body">
        <p>
            @Html.ActionLink("Create New", "Create", new { id = ID }) |
            @Html.ActionLink("Back to Vehicle List", "Index", "Vehicles", new object { }, null)
        </p>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.VideoUrl)
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vehicle.Title)
                    </td>
                    <td>
                        @cloudinary.Api.UrlImgUp.Transform(new Transformation().Width(200).Height(200).Crop("fill")).BuildImageTag(@item.PublicKey)
                        @*<img src=@Html.DisplayFor(modelItem => item.ImageUrl) alt="" width="200" height="200" />*@
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.VideoUrl)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
</section>

VehicleSale/Views/VehicleImages/Manage.cshtml
@model IEnumerable<ClassLibrary1.VehicleImage>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-xs-6 col-md-3">
            <a href="#" class="thumbnail">
                <img  style="height:150px;width:200px" src="@item.ImageUrl" />
            </a>
        </div>
    }

    @for (int i = 0; i < (12 - Model.Count()); i++)
    {
        <div class="col-xs-6 col-md-3">
            <a href="#" class="thumbnail">
                <img  style="height:150px;width:200px" src="~/Content/dropzone/images/noimage.png" />
            </a>
        </div>
    }

</div>